/**
 * PDF renderer — converts the HTML report to a self-contained PDF.
 *
 * Uses Puppeteer (headless Chrome) to render the full HTML report,
 * preserving all styling, collapsible sections, and visual layout.
 *
 * Usage:
 *   const { renderResultsPdf } = require('./pdf');
 *   await renderResultsPdf(htmlContent, outputPath);
 */

'use strict';

const { c } = require('../utils/colors');

/**
 * Render an HTML string to a PDF file.
 *
 * @param {string} htmlContent - The full self-contained HTML string
 * @param {string} outputPath  - Absolute path for the output .pdf file
 * @param {object} [options]   - PDF options
 * @param {string} [options.format='A4']     - Page size (A4, Letter, etc.)
 * @param {boolean} [options.landscape=false] - Landscape orientation
 * @param {string} [options.margin]          - CSS margin (e.g. '1cm')
 * @returns {Promise<{ path: string, pages: number, bytes: number }>}
 */
async function renderResultsPdf(htmlContent, outputPath, options = {}) {
  let browser;
  try {
    const puppeteer = require('puppeteer');
    browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });

    const page = await browser.newPage();

    // Set HTML content with generous timeout for complex reports
    await page.setContent(htmlContent, {
      waitUntil: 'networkidle0',
      timeout: 30000,
    });

    // Expand all collapsible sections so they appear in PDF
    await page.evaluate(() => {
      document.querySelectorAll('details').forEach(d => d.setAttribute('open', ''));
    });

    // Generate PDF
    const margin = options.margin || '1.5cm';
    const pdfBuffer = await page.pdf({
      path: outputPath,
      format: options.format || 'A4',
      landscape: !!options.landscape,
      printBackground: true,
      margin: { top: margin, right: margin, bottom: margin, left: margin },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 9px; color: #888; width: 100%; text-align: center; padding: 0 1.5cm;">
          <span>Generated by taskex</span>
          <span style="float: right;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
    });

    // Get page count from the buffer metadata
    const pages = pdfBuffer.toString('ascii').match(/\/Type\s*\/Page\b/g)?.length || 0;

    return {
      path: outputPath,
      pages,
      bytes: pdfBuffer.length,
    };
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      throw new Error(
        'PDF generation requires puppeteer. Install it with: npm install puppeteer\n' +
        '  This downloads a bundled Chromium (~300MB) for rendering.'
      );
    }
    throw new Error(`PDF generation failed: ${err.message}`);
  } finally {
    if (browser) {
      await browser.close().catch(() => {});
    }
  }
}

module.exports = { renderResultsPdf };
